version: '3'
services:

  crypto:
    build: .
    command: bash -c "rails server -b '0.0.0.0'"
    volumes:
      - ".:/app"
    ports:
      - "3000:3000"
    depends_on:
      - db
    environment:
      RAILS_ENV: development
      KEY: '54E4E332-178E-4549-9481-9D712AA32497'
      KEY2: '79B0BCAF-8025-4892-BC6D-ACDE1CFC3349'

  db:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongouser
      MONGO_INITDB_ROOT_PASSWORD: mongopassword

volumes:
  mongo-data:
