
development:
  clients:
    default:
      database: crypto
      hosts:
        - db:27017
      options:
        user: 'mongouser'
        password: 'mongopassword'
        auth_source: admin 

test:
  clients:
    default:
      database: crypto_test
      hosts:
        - localhost:27018
      options:
        user: mongouser
        password: mongopassword

        